name: "SAST - Horusec CLI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download Horusec Security
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
        
    - name: Running Horusec Scan
      run: |
        mkdir reports
        horusec start -p="./" -i=".**" --log-level='error' --output-format='text' --json-output-file="./reports/horusec_report.txt"
        
    - name: Upload Horusec Report
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: reports
